services:
  mysql:
    image: mysql:8.0
    container_name: barlacteo_mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: barlacteo_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  inventario:
    build:
      context: ./inventario
      dockerfile: Dockerfile
    container_name: barlacteo_inventario
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    networks:
      - app-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/barlacteo_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: 1234

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge