version: '3.8'
services:
  app:
    image: inventario:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://barlacteo_mysql:3306/barlacteo_db?autoReconnect=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=1234
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=com.mysql.cj.jdbc.Driver
      - SPRING_JPA_HIBERNATE_DDL_AUTO=create-drop
      - SPRING_JPA_DEFER_DATASOURCE_INITIALIZATION=true
      - SPRING_JPA_SHOW_SQL=true
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL8Dialect
      - SPRING_SQL_INIT_MODE=always
      - SPRING_SQL_INIT_PLATFORM=mysql
      - SPRING_APPLICATION_NAME=inventario
    networks:
      - mysql-network

networks:
  mysql-network:
    name: db_app-network
    external: true